#!/bin/sh
# Copyright (c) 2013 Cristian Patrasciuc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

TEST_FOLDER=`dirname $0`
python -B -m unittest discover -v -c -s $TEST_FOLDER -t $TEST_FOLDER
